version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: on-failure:3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    env_file:
      - .env
volumes:
  postgres: ~
